# Generated by Django 5.2.3 on 2025-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('paid_by', models.CharField(choices=[('Satya', 'Satya'), ('Friend1', 'Friend1'), ('Friend2', 'Friend2'), ('Friend3', 'Friend3')], max_length=100)),
            ],
        ),
    ]
